title: The Synthesist
description: Music portfolio of a composer, producer, and sound designer.
baseurl: "/thesynthesist" # the name of your repo
url: "https://thesynthesist.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
